# Cloud Build configuration for ACF REST API Plugin
# Triggers on push to main/master branch
#
# Required substitutions (set in Cloud Build trigger):
# - _BUCKET: Your GCS bucket name (e.g., my-wp-plugins)
# - _PLUGIN_SLUG: Plugin folder name (default: acf-rest-api)

steps:
  # Step 1: Extract version from plugin header
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'extract-version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Plugin file is in root, not in subfolder
        VERSION=$(grep -oP "Version:\s*\K[0-9.]+" ${_PLUGIN_SLUG}.php)
        if [ -z "$VERSION" ]; then
          echo "❌ Could not extract version from ${_PLUGIN_SLUG}.php"
          exit 1
        fi
        echo "✅ Detected version: $VERSION"
        echo "$VERSION" > /workspace/version.txt

  # Step 2: Create plugin ZIP file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'create-zip'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y zip
        VERSION=$(cat /workspace/version.txt)
        echo "Creating ZIP for version $VERSION"
        
        # Create build directory
        mkdir -p build/${_PLUGIN_SLUG}
        
        # Copy all plugin files to build folder (with correct folder structure)
        cp -r ${_PLUGIN_SLUG}.php build/${_PLUGIN_SLUG}/
        cp -r includes build/${_PLUGIN_SLUG}/ 2>/dev/null || true
        cp -r assets build/${_PLUGIN_SLUG}/ 2>/dev/null || true
        cp -r languages build/${_PLUGIN_SLUG}/ 2>/dev/null || true
        cp readme.txt build/${_PLUGIN_SLUG}/ 2>/dev/null || true
        
        # Create ZIP with plugin folder structure
        cd build
        zip -r ${_PLUGIN_SLUG}-${VERSION}.zip ${_PLUGIN_SLUG}
        
        # Also create latest.zip for convenience
        cp ${_PLUGIN_SLUG}-${VERSION}.zip ${_PLUGIN_SLUG}-latest.zip
        
        echo "✅ ZIP files created successfully"
        ls -la *.zip
        
        # Show contents
        echo "📦 ZIP contents:"
        unzip -l ${_PLUGIN_SLUG}-${VERSION}.zip

  # Step 3: Generate plugin-info.json
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'generate-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y jq
        VERSION=$(cat /workspace/version.txt)
        BUCKET=${_BUCKET}
        SLUG=${_PLUGIN_SLUG}
        DATE=$(date -u +"%Y-%m-%d %H:%M:%S")
        
        # Extract plugin info from main file
        PLUGIN_FILE="${SLUG}.php"
        PLUGIN_NAME=$(grep -oP "Plugin Name:\s*\K.+" $PLUGIN_FILE | head -1)
        PLUGIN_URI=$(grep -oP "Plugin URI:\s*\K.+" $PLUGIN_FILE | head -1)
        DESCRIPTION=$(grep -oP "Description:\s*\K.+" $PLUGIN_FILE | head -1)
        AUTHOR=$(grep -oP "Author:\s*\K.+" $PLUGIN_FILE | head -1)
        AUTHOR_URI=$(grep -oP "Author URI:\s*\K.+" $PLUGIN_FILE | head -1)
        REQUIRES_WP=$(grep -oP "Requires at least:\s*\K.+" $PLUGIN_FILE | head -1)
        REQUIRES_PHP=$(grep -oP "Requires PHP:\s*\K.+" $PLUGIN_FILE | head -1)
        TESTED_WP=$(grep -oP "Tested up to:\s*\K.+" $PLUGIN_FILE | head -1)
        
        # Set defaults if not found
        PLUGIN_NAME=${PLUGIN_NAME:-"ACF REST API Extended"}
        REQUIRES_WP=${REQUIRES_WP:-"5.8"}
        REQUIRES_PHP=${REQUIRES_PHP:-"7.4"}
        TESTED_WP=${TESTED_WP:-"6.4"}
        
        echo "Plugin Name: $PLUGIN_NAME"
        echo "Version: $VERSION"
        
        # Read existing plugin-info.json or create new one
        if [ -f "plugin-info.json" ]; then
          cp plugin-info.json build/plugin-info.json
        else
          echo '{}' > build/plugin-info.json
        fi
        
        # Update the JSON with new version info
        cd build
        jq --arg v "$VERSION" \
           --arg url "https://storage.googleapis.com/${BUCKET}/${SLUG}/${SLUG}-${VERSION}.zip" \
           --arg date "$DATE" \
           --arg name "$PLUGIN_NAME" \
           --arg tested "$TESTED_WP" \
           --arg requires "$REQUIRES_WP" \
           --arg requires_php "$REQUIRES_PHP" \
           '.version = $v | .download_url = $url | .last_updated = $date | .name = $name | .tested = $tested | .requires = $requires | .requires_php = $requires_php' \
           plugin-info.json > plugin-info-updated.json
        
        mv plugin-info-updated.json plugin-info.json
        
        echo "✅ Generated plugin-info.json:"
        cat plugin-info.json

  # Step 4: Upload ZIP files to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-zip'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/version.txt)
        
        # Upload versioned ZIP
        gsutil cp build/${_PLUGIN_SLUG}-${VERSION}.zip \
          gs://${_BUCKET}/${_PLUGIN_SLUG}/${_PLUGIN_SLUG}-${VERSION}.zip
        
        # Upload latest ZIP
        gsutil cp build/${_PLUGIN_SLUG}-latest.zip \
          gs://${_BUCKET}/${_PLUGIN_SLUG}/${_PLUGIN_SLUG}-latest.zip
        
        echo "✅ Uploaded ZIP files"

  # Step 5: Upload plugin-info.json to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Upload with no-cache header for immediate updates
        gsutil -h "Cache-Control:no-cache, max-age=0" \
          cp build/plugin-info.json \
          gs://${_BUCKET}/${_PLUGIN_SLUG}/plugin-info.json
        
        echo "✅ Uploaded plugin-info.json"

  # Step 6: Set public access on files
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'set-permissions'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/version.txt)
        
        # Make files publicly readable
        gsutil acl ch -u AllUsers:R gs://${_BUCKET}/${_PLUGIN_SLUG}/${_PLUGIN_SLUG}-${VERSION}.zip
        gsutil acl ch -u AllUsers:R gs://${_BUCKET}/${_PLUGIN_SLUG}/${_PLUGIN_SLUG}-latest.zip
        gsutil acl ch -u AllUsers:R gs://${_BUCKET}/${_PLUGIN_SLUG}/plugin-info.json
        
        echo "✅ Set public access"

  # Step 7: Deployment Summary
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'summary'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION=$(cat /workspace/version.txt)
        
        echo ""
        echo "========================================"
        echo "🎉 Deployment Complete!"
        echo "========================================"
        echo ""
        echo "Plugin: ${_PLUGIN_SLUG}"
        echo "Version: ${VERSION}"
        echo ""
        echo "📁 Files deployed:"
        echo "  • ZIP: https://storage.googleapis.com/${_BUCKET}/${_PLUGIN_SLUG}/${_PLUGIN_SLUG}-${VERSION}.zip"
        echo "  • Latest: https://storage.googleapis.com/${_BUCKET}/${_PLUGIN_SLUG}/${_PLUGIN_SLUG}-latest.zip"
        echo "  • Info: https://storage.googleapis.com/${_BUCKET}/${_PLUGIN_SLUG}/plugin-info.json"
        echo ""
        echo "⏰ WordPress sites will detect this update within 12 hours"
        echo "   (or immediately via 'Check for updates' link)"
        echo "========================================"

# Substitution defaults
substitutions:
  _BUCKET: 'your-plugin-bucket'
  _PLUGIN_SLUG: 'acf-rest-api'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '300s'
